ovs_perf: Conversion Python2 to Python3
chaudron/ovs_perf pull request #18
Opened 2018-04-13 20:21 UTC by Nandan307

Hi Eelco,

Kindly review the changes and get back to me.

This works in Python2 and Python3 and looks very clean too.
I have finished PVP and PP tests for L2 and L3 
in Python2 and Python3 with TRex and Xena.

Regards,
Nandan

2018-04-16 13:36 UTC, chaudron commented on CONTRIBUTORS
> +Vlad Buslov		tailcall@icloud.com
Please re-add the new line...

2018-04-16 13:36 UTC, chaudron commented on ovs_performance.py
> +
Any specific reason for adding this? If not please remove the extra CR/LF

2018-04-16 13:36 UTC, chaudron commented on ovs_performance.py
> +
Please remove CR/LF you added

2018-04-16 13:36 UTC, chaudron commented on traffic_generator_xena.py
> +        if (len(L2/L3/L4) + 4) > packet_size:  # +4 for Ethernet CRC
This code is also in traffic_generator_trex.py so it needs fixing there also

2018-04-17 11:08 UTC, chaudron requested changes
Please test with XENA as its sending out carbage...

2018-04-20 13:28 UTC, Nandan307 commented
This works in Python2 and Python3 and looks very clean too.
I have finished PVP and PP tests for L2 and L3
in Python2 and Python3 with TRex and Xena.

2018-05-08 12:47 UTC, chaudron approved these changes

2018-05-08 14:45 UTC, merged

2018-05-08 14:47 UTC, chaudron commented
Thanks, Nandan I've merged your changes. I tested almost all possible options, including DPDK and kernel datapath. Guess we need to start thinking about automation.