Additional p2p fixes
chaudron/ovs_perf pull request #7
Opened 2018-01-30 21:00 UTC by orgcandman

These are some additional fixes when using DPDK for p2p testing.

2018-02-23 09:39 UTC, chaudron requested changes
See comments

2018-02-23 09:39 UTC, chaudron commented on ovs_performance.py
> +                command += "-- set Interface {1} options:n_rxq={2} " \
Should this not be {0}, {1}, {2}?

2018-02-23 09:39 UTC, chaudron commented on ovs_performance.py
> +            command += "-- set Interface {1} type=dpdkvhostuser ". \
Should be {0}

2018-02-23 09:39 UTC, chaudron commented on ovs_performance.py
> +                       "other_config:pmd-rxq-affinity={3} " . \
Option numbers are messed up here also...

2018-02-26 16:19 UTC, orgcandman commented on ovs_performance.py
> +                command += "-- set Interface {1} options:n_rxq={2} " \
Weird.  I'll go back through everything and check how it's all working.  Actually, I don't know if I ever tested the virtual case again, so I probably messed them all up.

Thanks for the review.

2018-04-04 19:57 UTC, orgcandman commented
Forgot to check in and push up the changes.  I've done so - let me know if anything else is lingering.

2018-04-06 06:37 UTC, merged

2018-04-06 06:37 UTC, chaudron commented
Thanks for pushing, applied!